import Header from "./Header";
import Main from "./Main";
import Categories from "./Categories";
import Features from "./Features";
import Banner from "./Banner";
import LatestProducts from "./LatestProducts";
import Blog from "./Blog";
import Footer from "./Footer";
import ItemCarts from "../ItemCarts";
import Card from "../../components/Card/Card";
import Usa from "../../assets/images/usaFlag.png";
import fruitVeg from "../../assets/images/fruitVeg.jpg";
import bannerleft from "../../assets/images/banner/xbanner-1.png";
import bannerright from "../../assets/images/banner/xbanner-2.png";
import image1 from "../../assets/images/latestproducts/xlp-1.png";
import image2 from "../../assets/images/latestproducts/xlp-2.png";
import image3 from "../../assets/images/latestproducts/xlp-3.png";
import payments from "../../assets/images/footer/payments.png";
import transplogo from "../../assets/images/transplogo.png";
import AsideNavbar from "./Main/AsideNavbar";
import Hero from "./Main/Hero";
import HeaderTop from "./Header/HeaderTop";
import HeaderContainer from "./Header/HeaderContainer";
import Skeleton from "@mui/material/Skeleton";
import Stack from "@mui/material/Stack";
import categoriesimages from "../../constants/categoriesimages/index";
import FeaturesProgress from "./Features/FeaturesContainer/FeaturesProgress";
import FeaturesItems from "./Features/FeaturesContainer/FeaturesItems";
import FeaturesHead from "./Features/FeatureHead";
import FeaturesContainer from "./Features/FeaturesContainer";
import ProductLatest from "../../pages/Home/LatestProducts/ProductLatest";
import ReviewProducts from "../../pages/Home/LatestProducts/ReviewProducts";
import TopRatedProducts from "../../pages/Home/LatestProducts/TopRatedProducts";
import ProductTextItem from "./LatestProducts/ProductTextItem";
import TitleBlog from "./Blog/TitleBlog";
import PostBlog from "./Blog/PostBlog";
import WidgetContact from "./Footer/WidgetContact";
import WidgetFooter from "./Footer/WidgetFooter";
import AboutFooter from "./Footer/AboutFooter";
import posts from "../../constants/blogimages";
import footerInfos from "../../constants/footerinfos";
import { featuresInfos, headersInfos } from "../../redux";
import {
  latestProductsHeaders,
  latestProducts,
} from "../../helpers/ProductsMockDatas/index";
import { Swiper, SwiperSlide } from "swiper/react";
import { Pagination, Navigation, Autoplay } from "swiper";
import { featureActions } from "../../redux/features-slice";
import { departmentListActions } from "../../redux/department-list-slice";
import { cartActions } from "../../redux/cart-slice";
import { heartActions } from "../../redux/heart-slice";
import {
  postOrderedItems,
  fetchOrderedItems,
} from "../../redux/cart-slice/get-cart-list";
import {
  fetchFeaturesImages,
  getLocaleLists,
} from "../../redux/features-slice/get-features-images";
import { v4 } from "uuid";
import { useSelector, useDispatch } from "react-redux";
import { getLocaleStorage, setLocaleStorage } from "../../utils/lStorage";
import {
  GlobalStyle,
  AppContainer,
  HeaderTag,
  HeaderTopMain,
  Container,
  Row,
  LeftSideMain,
  LeftSideInner,
  LeftSideUL,
  LeftSideList,
  RightSideMain,
  RightSideInner,
  RightSideSocial,
  RightSideLanguage,
  RightSideAuth,
  LanguageFlag,
  SocialIcon,
  ArrowDown,
  LanguageWord,
  LanguageLists,
  LanguageListElement,
  LanguageListAnchor,
  LoginAnchor,
  HeaderContainerMain,
  LogoLeftSide,
  LogoContainer,
  LogoAnchor,
  LogoImg,
  MenuMiddleSide,
  MiddleSideNav,
  Menu,
  MenuList,
  MenuListItem,
  PagesList,
  PagesListElement,
  PagesListAnchor,
  Cart,
  CartInner,
  CartLists,
  CartList,
  CartListItem,
  CartPrice,
  CartQuantity,
  SectionHero,
  HeroRow,
  Aside,
  AsideCategories,
  AllDepartments,
  DepartmentsList,
  DepartmentList,
  DepartmentItem,
  HeroContainer,
  HeroSearch,
  HeroSearchFormContainer,
  HeroSearchForm,
  HeroSearchCategories,
  HeroInput,
  HeroFormButton,
  HeroSearchPhoneContainer,
  HeroSearchPhoneIcon,
  HeroSearchPhoneText,
  PhoneTextNumber,
  PhoneNumberTime,
  HeroAdvertisement,
  HeroText,
  HeroTextName,
  HeroTextGuarantee,
  HeroTextInfo,
  ShopButton,
  CategoriesSection,
  CategoriesRow,
  swiperSlide,
  slideHeader,
  FeaturesSection,
  FeatureContainer,
  FeatureRow,
  FeatureInner,
  FeatureTitleContainer,
  FeatureHeader,
  FeaturedControls,
  FeaturedLists,
  FeaturedList,
  FeatureItemsContainer,
  FeatureItemContainer,
  FeatureItemImage,
  FeatureImageIcons,
  FeatureImageIcon,
  FeatureImageAnchor,
  FeatureItemText,
  FeatureItemName,
  FeaturedItemAnchor,
  FeatureItemCost,
  BannerMain,
  BannerRow,
  BannerHalfSide,
  BannerImageContainer,
  BannerImage,
  ProductsLatest,
  LatestContainer,
  LatestProductsRow,
  LatestProductCol,
  LatestProductTextItem,
  SliderItem,
  SliderItemInner,
  SliderItemContainer,
  ItemPic,
  ItemText,
  LatestItemImg,
  LatestItemHeader,
  BlogSection,
  RowHelper,
  BlogTitleContainer,
  BlogTitle,
  BlogHeader,
  BlogPost,
  PostItem,
  PostImageContainer,
  PostImage,
  PostTextContainer,
  DateComInfos,
  ReleaseDate,
  PostComment,
  PostName,
  PostInfos,
  FooterSection,
  FooterAboutCol,
  FooterAboutLogo,
  AboutLists,
  FooterAbout,
  AboutList,
  FooterWidgetCol,
  FooterWidget,
  WidgetLists,
  FooterWidgetContactCol,
  WidgetForm,
  SubscribeBtn,
  WidgetAnchor,
  BottomFooterCol,
  FooterCopyRight,
  CopyRightText,
  FooterPayment,
  ShopCartContainer,
  DefaultShopContainer,
  TopScrollContainer,
  CartItemContainer,
  CartItemImageContainer,
  CartItemInfosContainer,
  TransparentHide,
  CartItemInfos,
  CartItemInfosSub,
  CartItemInfo,
  CartIncDecContainer,
  CartButtonsContainer,
  CartButtonsSub,
  CartButton,
  CartHeader,
  CartTotalsInfos,
  CartEmpty,
  CartItemName,
  WishListItemContainer,
  WishListsItemImageContainer,
  WishListsColumnName,
  WishListItemInfos,
  WishListItemInfo,
  WishListButtonContainer,
} from "../../components/styledcomponents/Home/index";

export {
  GlobalStyle,
  AppContainer,
  WishListItemContainer,
  WishListsItemImageContainer,
  WishListsColumnName,
  WishListItemInfos,
  WishListItemInfo,
  WishListButtonContainer,
  Header,
  HeaderTag,
  HeaderTopMain,
  Container,
  Row,
  LeftSideMain,
  LeftSideInner,
  LeftSideUL,
  LeftSideList,
  RightSideMain,
  RightSideInner,
  RightSideSocial,
  RightSideLanguage,
  RightSideAuth,
  LanguageFlag,
  SocialIcon,
  LanguageWord,
  ArrowDown,
  LanguageLists,
  LanguageListElement,
  LanguageListAnchor,
  LoginAnchor,
  HeaderContainerMain,
  LogoLeftSide,
  LogoContainer,
  LogoImg,
  LogoAnchor,
  MenuMiddleSide,
  MiddleSideNav,
  Menu,
  MenuList,
  MenuListItem,
  PagesList,
  PagesListElement,
  PagesListAnchor,
  Cart,
  CartInner,
  CartLists,
  CartList,
  CartListItem,
  CartPrice,
  CartQuantity,
  Main,
  SectionHero,
  HeroRow,
  Aside,
  AsideCategories,
  AllDepartments,
  DepartmentsList,
  DepartmentList,
  departmentListActions,
  DepartmentItem,
  HeroContainer,
  HeroSearch,
  HeroSearchFormContainer,
  HeroSearchForm,
  HeroSearchCategories,
  HeroInput,
  HeroFormButton,
  HeroSearchPhoneContainer,
  HeroSearchPhoneIcon,
  HeroSearchPhoneText,
  PhoneTextNumber,
  PhoneNumberTime,
  HeroAdvertisement,
  HeroText,
  HeroTextName,
  HeroTextGuarantee,
  HeroTextInfo,
  ShopButton,
  fruitVeg,
  Categories,
  CategoriesSection,
  CategoriesRow,
  swiperSlide,
  slideHeader,
  categoriesimages,
  Swiper,
  SwiperSlide,
  Pagination,
  Navigation,
  Autoplay,
  Features,
  FeaturesSection,
  FeatureContainer,
  FeatureRow,
  FeatureInner,
  FeatureTitleContainer,
  FeatureHeader,
  FeaturedControls,
  FeaturedLists,
  FeaturedList,
  featureActions,
  FeatureItemsContainer,
  FeatureItemContainer,
  FeatureItemImage,
  fetchFeaturesImages,
  getLocaleLists,
  FeatureImageIcons,
  FeatureImageIcon,
  FeatureImageAnchor,
  FeatureItemText,
  FeatureItemName,
  FeaturedItemAnchor,
  FeatureItemCost,
  FeaturesContainer,
  FeaturesHead,
  Banner,
  BannerMain,
  BannerRow,
  BannerHalfSide,
  BannerImageContainer,
  BannerImage,
  bannerleft,
  bannerright,
  LatestProducts,
  ProductLatest,
  ReviewProducts,
  TopRatedProducts,
  ProductsLatest,
  LatestContainer,
  LatestProductsRow,
  LatestProductCol,
  LatestProductTextItem,
  SliderItem,
  SliderItemInner,
  SliderItemContainer,
  ItemPic,
  ItemText,
  LatestItemImg,
  LatestItemHeader,
  Blog,
  BlogSection,
  RowHelper,
  BlogTitleContainer,
  BlogTitle,
  BlogHeader,
  BlogPost,
  PostItem,
  PostImageContainer,
  PostImage,
  PostTextContainer,
  DateComInfos,
  ReleaseDate,
  PostComment,
  PostName,
  PostInfos,
  AboutLists,
  Footer,
  FooterSection,
  FooterAboutCol,
  FooterAboutLogo,
  FooterAbout,
  AboutList,
  FooterWidgetCol,
  FooterWidget,
  WidgetLists,
  FooterWidgetContactCol,
  WidgetForm,
  SubscribeBtn,
  WidgetAnchor,
  BottomFooterCol,
  FooterCopyRight,
  CopyRightText,
  FooterPayment,
  TitleBlog,
  PostBlog,
  posts,
  ProductTextItem,
  FeaturesItems,
  FeaturesProgress,
  v4,
  Skeleton,
  Stack,
  useSelector,
  useDispatch,
  Hero,
  AsideNavbar,
  HeaderTop,
  HeaderContainer,
  AboutFooter,
  WidgetFooter,
  WidgetContact,
  ItemCarts,
  Card,
  featuresInfos,
  headersInfos,
  cartActions,
  ShopCartContainer,
  DefaultShopContainer,
  TopScrollContainer,
  CartItemContainer,
  CartItemImageContainer,
  CartItemInfosContainer,
  TransparentHide,
  CartItemInfos,
  CartItemInfosSub,
  CartItemInfo,
  CartIncDecContainer,
  CartButtonsContainer,
  CartButtonsSub,
  CartButton,
  CartHeader,
  CartTotalsInfos,
  CartEmpty,
  CartItemName,
  heartActions,
  latestProducts,
  latestProductsHeaders,
  footerInfos,
  getLocaleStorage, 
  setLocaleStorage,
  postOrderedItems,
  fetchOrderedItems,
  image1,
  image2,
  image3,
  transplogo,
  payments,
  Usa,
};
